apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: taskira
  labels:
    name: todo-app
    app: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: ghcr.io/demiguise2360/todo-app:v1
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_URI
          value: "mongodb://todo-mongo-service:27017/todoapp"
        - name: JWT_SECRET
          value: "blablabla"
        - name: NODE_ENV
          value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: taskira
  labels:
    name: todo-app
    app: todo-app
spec:
  selector:
    app: todo-app
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000